### ISSUE TITLE
Add Barnes Hut algorithm

### ISSUE THREAD

**Issue by HugoGranstrom** [TheHappyKoala/Harmony-of-the-Spheres#40] opened 2019-04-26 20:48 UTC
I thought I should start working with this at last now when you have been kind enough to create the vectors 😁 I'm still in the "grasping my head around it"-stage so there won't be much code in a while. 

I have a few implementation questions for how it should be used. Right now we have a function for calculating the acceleration the slow way. Should Barnes Hut be a drop-in replacement to that function? 
What type of data structure do you think is most suitable for the nodes? It should have a position, length, center of mass vector and a list of its children nodes. 
And last, how do we determine what size the largest cube should be?

**Comment by TheHappyKoala** [comment] 2019-04-27 11:41
Yaaayyyy... Very happy to hear that. I guess there is no getting around the fact that one has to start somewhere! Super excited about what Barnes Hut could do for the galaxy simulations, in particular, and perhaps, at a later stage, even a cheap protoplanetary disk scenario!

I need to push a fix for a bug that I somehow managed to spawn, probably through my good old gitigans tendencies, in the scene module, but the fix has already been implemented so that should be up in an hour or two, and then you can do a Git pull on the master branch. 

I have added TypeScript to the stack and my goal is to migrate the core modules from JS to TS, as TypeScript is just a saner language than JavaScript in that it is statically typed and with VS Code (no idea which editor you are using, but if you want to leverage the full power of TS, that is the editor to use) it really makes the whole process of writing and debugging code more of a pleasure, and it becomes transparent since every method has a statically defined signature that is linted by the compiler before it compiles the TS into JS. To see what I am talking about, check [this](https://github.com/TheHappyKoala/Harmony-of-the-Spheres/blob/even_more_typescript/src/js/Physics/Integrators/Euler.ts) out. The type checking only works when a typescript file is used in another typescript file, so it will take converting a few modules into TS before the benefits start showing up, but I feel it is the way to go, regardless. And hey, you get private members and methods, too :rofl: I will add the TS work I have in staging to the commit that fixes the bug that I mentined earlier later today. 

Feel free to let me know what you think about TS and if you have any questions; always open to feedback! Oh yea, and the most important thing... Let me know if your project runs after you have pulled the latest changes..... I have made so many changes to the stack that I am a bit nervous, but it runs on my computer, at least :rofl: '

I will get back to you in a bit with some remarks regarding your questions about the Europa Clipper as well as the Barnes Huts project, because a project it is :smile: . Need to read up on the specifics so I know what I am talking about and not wasting your time before I start brainfarting all over the place :hankey:

**Comment by TheHappyKoala** [comment] 2019-04-27 17:50
Lol, everything should be working fine, now! If you bump into something, let me know, and I'll look into it pronto.

Couldn't stop myself from finally adding something I've wanted to add for a very long time: a git commit hook that runs prettier, so that you don't have to run it yourself! So you no longer have to run prettier yourself; whenever you make a commit, a script will do that for you. Will save me a lot of embarrassing commits along the lines of "cleanup, uh" because I forgot to prettify the code before committing it... Well, no more! 

Note: you will probably have to run npm install after you have pulled all of these changes, as a lot of packages have been added and removed. 

Regarding the Europa Clipper scenario, my reason for not opting for el diablo A.K.A RKN12 is that trajectory correction manoeuvres for this mission only had dates associated with them, and not the exact time, so I had to do some guess work to get those manoeuvres right, and given that constraint, it was easier to work with a fixed time step. As for why I didn't use the Yoshida integrator... Can't really provide a good answer, I'm afraid, other than that I was probably stuck in my old well trodden ways, haha... "I'm not going to try anything new on the menu, because I know I like this option every time I have it" - a crappy mindset to have, so thanks for asking me a question that had me thinking about why I made the choice that I made. 

Haven't had time to properly read up on BH yet, so I'll probably get back to you with some feedback tomorrow... mañana, mañana!

**Comment by TheHappyKoala** [comment] 2019-04-27 17:59
Oh, by the way, I actually have a half-finished Horizons client, so I'll get that up and running soon enough, albeit in a separate repository since it could be used for other projects... Gonna make it an npm module that we can then install as a dependency using npm i --save-dev [package name]

I'll crawl back under my rock, now! 🤣

**Comment by HugoGranstrom** [comment] 2019-04-28 16:44
Ah, the gitigans again 🤣 Did a fresh pull and it runs on my machine as well 😉 Seems like they are were sorted out. 

I'm also using VS Code so it's a perfect fit with TS ;-) Javascript can be quite a mess sometimes 😅 I have never used TS before, though so there might be some Javascript frogs jumping out of my mouth still 🤣 I guess I should start using it right away when (I eventually 😅) start coding the BH. 

I have heard lots of good stuff about commit hooks so this is a great idea. I've been a bit forgetful about it as well hehe... 

The power of RKN12 can be hard to tame sometimes, I totally understand your reasoning ;-) Regarding Yoshida/RKN6 I think it doesn't really matter that much. Yoshida is symplectic and of order 6 while RKN6 isn't and is of order 7 (I think). And we are looking at such a small period of time so the effects of the higher order probably outweighs the symplecticness 😉. 

Awesome! The client will bring less work for you as well when setting up the scenarios ;-) I remember when I was there my first time, I copy-pasted all the coordinates from their web-interface 🤣

**Comment by HugoGranstrom** [comment] 2019-05-01 10:07
Good news! I have managed to build a working version in Python (my strongest language) so now it's just a matter of converting it to Typescript and HotS 🎆 🚀

**Comment by HugoGranstrom** [comment] 2019-05-01 10:44
I did some benchmarking comparing PEFRL with and without BH.
N = 100 planets:
Brute force: 4.6 seconds
BH: 12.6 seconds
N = 1000 planets:
Brute force: 382 seconds
BH: 212 seconds

BH seems to overtake the brute force method somewhere between 100-1000 planets and is nearly 2X faster then.

**Comment by TheHappyKoala** [comment] 2019-05-01 14:08
Woho... :rocket:   :rocket:   :rocket:   :rocket:   :rocket:  !!! That's amazing. 

What was the benchmark that you were testing the algorithms against??? 

I'm going to merge the current TypeScript branch I have open and get back to working on features for a bit... Hearing about your progress makes me way too excited to just spend my time on tidying shit up all the time... So much for my wisdom and emerging locks of grey hair :rofl: :rofl: :rofl: 

Quick quesiton, the BH implementation, it has a fixed time step, no? Asking as if that's not the case, I'll just migrate the adaptive time step integrators to TypeScript in case BH relies on one of those base classes in one way or another, although I suspect that is not the case, but figured I would ask anyways :koala: 

Hihi, I just downloaded a paper on globular clusters and their gravitational dynamics... I wonder why :thinking: !

**Comment by TheHappyKoala** [comment] 2019-05-01 14:10
Just merged the branch I had open!

**Comment by HugoGranstrom** [comment] 2019-05-01 14:15
I ran two simulations with 100 and 1000 planets for a period of 20 days with a timestep of 1 day. Both with PEFRL integrator. I ran this on my laptop with a i3 so not the fastest chip 😅 Hopefully the TS version should be a bit faster. 

Haha 🤣 good to hear you are human as well. 

As I have implemented it, it is just a drop-in replacement for our current acceleration method so it should work with all of our integrators pretty much out of the box. 🚀 

Exciting, will be looking forward to some galatic simulations 😉

**Comment by HugoGranstrom** [comment] 2019-05-01 14:22
Implementation question: I have a few functions that I use in my implementation, should I add all to Euler.ts or does it become to cluttered then?

**Comment by TheHappyKoala** [comment] 2019-05-01 14:56
Hms, I would create a separate base class altogether for the BH algorithm. It's a new way of solving the equations of gravity and motion, which is to say it does not draw on a brute force approach, so I think it should be the root of its own tree.

**Comment by TheHappyKoala** [comment] 2019-05-01 14:57
And I just ran into a TS refactoring error... Why do I keep on doing this to myself 😭 . Lol, nah, the rain shall pass and give way to sun shine and [insert n cliches of your choice].

**Comment by HugoGranstrom** [comment] 2019-05-01 15:01
I could also see that we integrate it into the base class we have and add a global variable that keeps track of which algorithm we are using. And then add an if statement in our current generateAccelleration function like this:

```
function generateAcceleration(stuff){
  if (useBarnesHut){
    // call new function
  } else {
    // do bruteforce
  }
}
```

This way all integrators would work right away without any modification on their part. What do you think?

**Comment by HugoGranstrom** [comment] 2019-05-01 15:02
After this is done I won't stand trees any more 🤣 🌳

**Comment by TheHappyKoala** [comment] 2019-05-01 15:05
That's actually a really good idea! Would be fun to let people compare the results of a solar system sim using some brute force method with those of using the BH method.

**Comment by TheHappyKoala** [comment] 2019-05-01 15:06
Hehehe, I did game theory at university, so needless to say I have a difficult relationship with all things structured like trees

**Comment by TheHappyKoala** [comment] 2019-05-01 15:20
Alright, fixed the issue. I was so confident when I created the code this little bug... Commit message included a "No need for x, so that goes..."; the corner of shame it is!

**Comment by HugoGranstrom** [comment] 2019-05-01 16:08
Ohhh 😢 those bugs are the worst if you don't spot them directly. 
Trees are the roots of evil maybe? 🤣😅

**Comment by HugoGranstrom** [comment] 2019-05-01 16:09
I'll begin to work right away then. Which scenario do you think would be the best to do my test it on?

**Comment by TheHappyKoala** [comment] 2019-05-01 16:14
I'm thinking the best idea would be to create a scenario where each mass is represented by a particle as opposed to a mesh, because simulating a thousand or so meshes will cause things to go poop regardless of how computationally intensive the integrator is. Right now I don't think there is a scenario that has enough masses in it for the benefits of BH to materialise, so I'd say this should be the first thing for me to focus on... Or do you have another ace up your sleeve?

**Comment by TheHappyKoala** [comment] 2019-05-01 16:16
Quick question... Could you add a softening constant as an optimal parameter for the BH class? Thinking this could be useful for simulating massive clouds of particles, since it would prevent the particles that make up the cloud from evaporating

**Comment by TheHappyKoala** [comment] 2019-05-01 16:17
Then I will add a slider for the softening constant to the UI... Maybe we should add that option to the brute force algos, as well?

**Comment by HugoGranstrom** [comment] 2019-05-01 16:19
That sounds like an awesome idea 😉 No more slingshots to infinity here! 

If you don't mind, a scenario like that would be awesome to see if everything work as they should 😄

**Comment by TheHappyKoala** [comment] 2019-05-01 16:26
Okay... I'm gonna give [this](https://en.wikipedia.org/wiki/Structure_formation) a go 🤣

**Comment by HugoGranstrom** [comment] 2019-05-01 16:28
That's some heavy stuff 🚀 Do you have a data center on your backyard perhaps? 🤣 Jokes aside, that could be interesting to see if it can run here 😉

**Comment by HugoGranstrom** [comment] 2019-05-01 21:11
I've got good news for you!!! I have managed to get Barnes Hut working with all of the integrators 🎉 Will commit it tommorow evening. Can't wait to let you try it out on a big simulation. 

Some quick thoughts about it thus far: The adaptive integrators are compatible with it but for a small number of planets it is notably slower then the brute force version but still tolerable.

**Comment by TheHappyKoala** [comment] 2019-05-19 20:49
Hey @HugoGranstrom !

Sorry for going awol, but I decided to treat my brain to a change of scenery code wise and finally develop the HORIZONS client we talked about.

It's still a work in progress, but you'll find what I have so far [here](https://github.com/TheHappyKoala/jpl-horizons-node-client)

You can probably get an idea of the API I have in mind, so if you see something that has you ask whether Darrell wrote that while tripping balls, do raise a flag 🎏 😆 

I just wrote an email to JPL asking if they're fine with us integrating this client with Harmony of the Spheres so that you can create new scenarios from scratch in the app itself, so let's wait and see if they are ok with that. If not, this will still greatly simplify the creation of new scenarios. I'm also going to write a separate cli for Harmony of the Spheres that will use this API to create scenarios, but I figured I would keep that separate since others might want to use this tool for reasons unrrelated to Harmony of the Spheres, in which case getting lots of Harmon of the Spheres related garbage data wouldn't be the nicest thing, lol. 

Oh well, have a good start to the week!

**Comment by HugoGranstrom** [comment] 2019-05-20 15:52
That seems like a really neat tool 😉 Now we soon could create a solar system starting from which date we want by just changing a date string 🚀 I'm already excited for what this could bring to the table :-D. 

The wise man Darrell shows up again ;-) will be interesting to see what they say. What reasons would they have for denying it? Bandwidth?

**Comment by TheHappyKoala** [comment] 2019-05-20 19:39
Totally :D! A real time solar system scenario would be kind of cool, too... 

I have no idea, but I doubt they would mind as another space app called [Asterank](http://www.asterank.com/) appears to draw on HORIZONS amongst other sources for its data, which is also available via a public API, so I'm just going to go ahead and whip up a gui for creating new scenarios with data pulled from HORIZONS. 

Gonna get set up a rest api with auth for the tool and get it up and running on Heroku so that we can start consuming it from Harmony of the Spheres. 

Asterank is a pretty damn cool app. Bit skeptical about the value estimates provided for asteroids there, though.. Ryugu worth 35 billion buckaroos in profits? It's a loosely held together rubble pile, and I doubt it is particularly rich in precious metals. My biggest question mark, though, is how the costs were estimated, since the technologies, logistics and so on that would enable asteroid mining are yet to be developed, and profits = revenues - costs, so my right eyebrow is pointing upwards right now.

**Comment by TheHappyKoala** [comment] 2019-05-21 06:29
Woho! I got an email back, and while it has to be confirmed by the web administrator for HORIZONS, the guy I wrote, Jon Giorgini, thought our use case would be fine... He said that they would not like a scenario where somebody queries the whole database of 800 000 (!!!!!!!) objects at once, but we won't do that, and it wouldn't even be possible with the code I've written, since the way I wrote it when you request a list of bodies a request is sent for the first body and only when it has been completed is the second request sent, so I'd say we are being really, really, really gentle to their servers. 

Anyhow, fingers crossed. This would add a whole other dimension to Harmony of the Spheres and basically make it a visualization tool for the HORIZONS system and all of the 800 000 bodies catalogued there!! 🚀 🚀 🚀

**Comment by HugoGranstrom** [comment] 2019-05-21 07:27
🤣 haha, they are before their time. What one sees as rubbish others see as treasure 😅

Great to hear! 😃 Do they have 800 000 objects!! 😮😅😵 I'm guessing most of those arr asteroids or comets. Nasa really has done a vast surveying of the night sky 🚀. That does sound like a relatively mild way of requesting data 😉 

It's strange that Nasa hasn't made one themselfs 😅🤔 they have the competence to do it.

**Comment by TheHappyKoala** [comment] 2019-05-21 21:02
And we're go :D! The web administrator said it's fine as long as there's only one request to Horizons per IP address at a time, and I struggle to envision a use case where somebody has two tabs open at once on their device making requests at exactly the same time to Horizons, so wiiieeee 🚀 !!! 

They have an app called [eyes on the solar system](https://eyes.nasa.gov/eyes-on-the-solar-system.html), but it's not a gravity simulator and it definitely does not enable you to visualize every object in the Horizons catalogue. I think the reason is quite simple, though: they have not received funding to create this kind of tool, and being funded by tax dollars, I guess they can't freestyle and create software on a whim unless it has some practical use. 

But couple that with this [database of asteroid 3d models](https://space.frieger.com/asteroids/) which I have received permission to use as long as I cite the names of the scientists that created the models I'm inclined to think that awesomely cool times are ahead 🚀 . 

It's gonna take some thinking though to figure out how to integrate the ability to create new scenarios with Horizons data into the app, though... Thinking that maybe the best way to go would be to have another menu with two options where one option is pre-made scenario and the other one is create a new scenario and then that section will have the option of pulling in data from Horizons... Does that make sense???

**Comment by HugoGranstrom** [comment] 2019-05-21 21:27
Woho! 👏😊 Now the fun can begin for real 🚀. 3d models, that's so cool 🤑 once again, one of the things that got me hocked on this project was the visuals and now we are getting even more 😎. 

That sounds reasonable, sadly. Nasa gets too little fundings compared to what they do and achieve. 

If I'm allowed to let my imagination run wild, it would be cool if you could save your custom scenarios locally (isn't there something called Local Storage nowadays) so the next time you load the page, you could choose to load custom scenario from the ones you have saved. This way if someone wants to run the same simulation multiple times they wouldn't need to fetch data from Horizons more than one time. And if we go even further away into the future this could be a way of sharing custom scenarios with others by just sharing a json/js/ts file with all the initial conditions. As I said this is my brain going bananas 🤣

**Comment by TheHappyKoala** [comment] 2019-05-23 06:16
Hahaha, the local storage thing should be very easy to implement! Good idea! I'll look into that.

But yes, I've thought about the ability to share simulations and so on, too, and this would bring the app one step closer to being a useful tool for researchers that want to communicate, for instance, their exoplanet discoveries to the public with a sexy visualisation... Bonkers and over ambitious, but that is where I want to get Harmony of the Spheres to.

Rolled out a really random build yesterday, by the way. It features awesome contributions like your Barnes Hut work, but also WTF-moments like the new twinkling particles option that you will find in the graphics section 🤣 , a twitter button and bucket loads of refactoring that will make our lives easier but won't really be noticeable by the user, but yea, that has to be done, too. 

Hope you're ok with it, but I decided against including our Twitter handles in the prefilled Share Scenario Tweet button. I just found it difficult to justify putting them there. Like "Check out this 3D gravity simulation of the Martian system and by the way @darrell @hugo" 🤣 If you'd like your handle there anyways, let me know, though, and I'll add it.

**Comment by HugoGranstrom** [comment] 2019-05-23 06:35
Nice we're on the same page 😉👍😁 

Neat! Now we just have to add a royalty free version of "Twinkle twinkle little star" 😜 jokes aside it was a cool experience seeing the particles twinkle 😉😁

I thought it wouldn't be so explicit, just som metadata for SEO 🤣 So a good call from your side 👏😉 it would look terrific 😅🤣

**Comment by TheHappyKoala** [comment] 2019-05-23 07:09
Lol, glad to hear that I didn't step on your toes by making that call 🤣 

Yea, it's way too prominent right now. I'm going to add some more share stuff and put them all in a small bar in the bottom right corner of the page. Not sure what I was thinking, but I do know one thing... Don't roll shit out just before midnight 🤣 Looked at it this morning and it kind of felt like I'd added a Coca Cola sign to the Notre Dam. 

I still like the idea of integrating seamless social media share functionality, though, as I think it'll be a great way of getting it out there to those that have an interest in these kinds of things, especially when you can create your own scenarios and save them to a data base 😮 ! 

This highlights one issue, though... I'm wearing way too many freaking hats at the moment, ui developer, do some physics too, tooling, social media manager (🤣 ), 3D graphics and so on... It's bucket loads of fun, but I'm gonna make an effort to bring on some people that could contribute to the UI development (there's quite a library of components that I have cobbled together, so I think it would be quite easy for people to pick up and make meaningful contributions). I would like to focus more on the graphics, HORIZONS integration and so on. 

Oh well, back to work 🤣

**Comment by HugoGranstrom** [comment] 2019-05-23 07:23
Sometimes, getting things in your face is a good thing 🤣 but the tab sounds like a more viable idea, especially if more social media is being added in the future, which is great! 😎😁 

Yeah, when you find something interesting and fun you can keep up a large workload but in the end it's wearing you down 🤔 You're like a modern Leonardo da Vinci, doing all kinds of stuff 😉🤣 When my exams are over in June I will try to release you of some of the load 😉 but more contributors would be truly awesome. Do you have any idea for getting people here except just asking for contribs on twitter/reddit etc?

**Comment by HugoGranstrom** [comment] 2019-05-23 14:54
Closed this as it has been released in a build

**Closed** 2019-05-23 14:54 UTC
